CREATE DATABASE QLTHUVIEN
GO
USE QLTHUVIEN
GO
CREATE TABLE THELOAI
(
	MATHELOAI VARCHAR(10) NOT NULL PRIMARY KEY,
	TENTHELOAI NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(MAX)
)
GO
CREATE TABLE TACGIA 
(
	MATACGIA VARCHAR(10) NOT NULL PRIMARY KEY,
	TENTACGIA NVARCHAR(50) NOT NULL,
	GHICHI NVARCHAR(MAX)
)
GO
CREATE TABLE NGONNGU
(	
	MANGONNGU VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNGONNGU NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(MAX)
)
GO
CREATE TABLE NHAXUATBAN
(
	MANXB VARCHAR(10) NOT NULL PRIMARY KEY,
	TENNXB NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(MAX)
)
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT,
	NGAYSINH DATE,
	DIACHI NVARCHAR(MAX),
	SDT VARCHAR(10),
	EMAIL VARCHAR(MAX),
	CCCD VARCHAR(12),
	PASSWORD VARCHAR(50) NOT NULL,
	CHUCDANH NVARCHAR(50) NOT NULL
)
GO
delete from docgia where manv = '1'
delete from nhanvien where manv = '1'
INSERT INTO dbo.NHANVIEN
VALUES
(   '1',   -- MANV - varchar(10)
    N'1',  -- HOTEN - nvarchar(50)
    1, -- GIOITINH - bit
    '08-15-2004', -- NGAYSINH - date
    N'Hàm Yên - Tuyên Quang', -- DIACHI - nvarchar(max)
    '0369623960', -- SDT - varchar(10)
    'giang@giang.com', -- EMAIL - varchar(max)
    '123456789JQK', -- CCCD - varchar(12)
    '1',   -- PASSWORD - varchar(50)
    N'Admin'   -- CHUCDANH - nvarchar(50)
    )
select * from nhanvien
GO
CREATE TABLE DOCGIA
(
	SOTHE VARCHAR(10) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT,
	NGAYSINH DATE,
	DIACHI NVARCHAR(MAX),
	SDT VARCHAR(10),
	EMAIL VARCHAR(MAX),
	CCCD VARCHAR(12),
	MANV VARCHAR(10) NOT NULL FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN,
	NGAYCAP DATE,
	NGAYHETHAN DATE
)
GO
CREATE TABLE SACH 
(
	MASACH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENSACH NVARCHAR(50) NOT NULL,
	SOLUONG INT,
	NGAYCN DATE,
	MANXB VARCHAR(10) NOT NULL FOREIGN KEY(MANXB) REFERENCES dbo.NHAXUATBAN,
	NGAYXB DATE, 
	SOTRANG INT,
	TRANGTHAI NVARCHAR(MAX)
)
GO
CREATE TABLE SACHCHITIET
(	
	ID int identity(1,1) not null PRIMARY KEY,
	MASACH VARCHAR(10)  NOT NULL FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH),
	MATACGIA VARCHAR(10) NOT NULL FOREIGN KEY(MATACGIA) REFERENCES dbo.TACGIA,
	MATHELOAI VARCHAR(10) NOT NULL FOREIGN KEY(MATHELOAI) REFERENCES dbo.THELOAI,
	MANGONNGU VARCHAR(10) NOT NULL FOREIGN KEY(MANGONNGU) REFERENCES dbo.NGONNGU
)
GO
CREATE TABLE PHIEUMUON
(
	MAMUON VARCHAR(10) NOT NULL PRIMARY KEY,
	SOTHE VARCHAR(10) NOT NULL FOREIGN KEY(SOTHE) REFERENCES dbo.DOCGIA,
	NGAYMUON DATE NOT NULL,
	HANTRA DATE NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	TRANGTHAI NVARCHAR(MAX)
)
GO
CREATE TABLE PHIEUMUONCT
(
	ID int identity(1,1) not null PRIMARY KEY,
	MAMUON VARCHAR(10) NOT NULL FOREIGN KEY(MAMUON) REFERENCES dbo.PHIEUMUON,
	MASACH VARCHAR(10) NOT NULL FOREIGN KEY(MASACH) REFERENCES dbo.SACH,
	SOLUONG INT
)
GO
CREATE TABLE PHIEUTRA
(
	MATRA VARCHAR(10) NOT NULL PRIMARY KEY,
	SOTHE VARCHAR(10) NOT NULL FOREIGN KEY(SOTHE) REFERENCES dbo.DOCGIA,
	NGAYMUON DATE NOT NULL,
	HANTRA DATE NOT NULL,
	NGAYTRA DATE NOT NULL,
	MANV VARCHAR(10) NOT NULL FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN,
	TRANGTHAI NVARCHAR(MAX)
)
GO
CREATE TABLE PHIEUTRACT
(
	ID int identity(1,1) not null PRIMARY KEY,
	MATRA VARCHAR(10) NOT NULL FOREIGN KEY(MATRA) REFERENCES dbo.PHIEUTRA,
	MASACH VARCHAR(10) NOT NULL FOREIGN KEY(MASACH) REFERENCES dbo.SACH,
	SOLUONG INT
)
GO
CREATE TABLE XULYVP
(
	MAXULY VARCHAR(10) NOT NULL PRIMARY KEY,
	MATRA VARCHAR(10) NOT NULL FOREIGN KEY(MATRA) REFERENCES dbo.PHIEUTRA,
	SOTHE VARCHAR(10) NOT NULL FOREIGN KEY(SOTHE) REFERENCES dbo.DOCGIA,
	MANV VARCHAR(10) NOT NULL  FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN,
	LYDOVP NVARCHAR(MAX),
	HTXULY NVARCHAR(MAX),
	NGAYXL DATE
)
GO
/*
Scaffold-DbContext "Data Source=HOANGTHANHGIANG\SQLEXPRESS;Initial Catalog=QLTHUVIEN;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
*/